#ifndef _COMM_H_
#define _COMM_H_

#define SUCC 		0
#define FAIL 		-1

enum status_code
{
	STATUS_OK = 0,
	STATUS_REQUEST_DECODE_ERR = 99,
	STATUS_REQUSET_NOT_POST_ERR = 100,
	STATUS_REQUSET_NOBODY_ERR = 101,
	STATUS_BODY_NOTJSON_ERR = 102,
	STATUS_HEAD_NOTJSON_ERR = 103,
	STATUS_APPID_NOTNUM_ERR = 104,
	STATUS_APPID_CHECK_ERR = 105,
	STATUS_TIME_NOTNUM_ERR = 106,
	STATUS_TIME_CHECK_ERR = 107,
	STATUS_SIGN_NOTSTRING_ERR = 108,
	STATUS_SIGN_CHECK_ERR = 109,
	STATUS_VERSION_NOTSTRING_ERR = 110,
	STATUS_VERSION_CHECK_ERR = 111,
	STATUS_REQINFO_NOTSTRING_ERR = 112,
	STATUS_REQINFO_CHECK_ERR = 113,
	STATUS_REQINFO_DECRYPT_MSG_ERR = 114,
	STATUS_REQINFO_NOTJSON_ERR = 115,
	STATUS_REQINFO_NOTARRARY_ERR = 116,
	STATUS_ID_NOTNUM_ERR = 117,
	STATUS_FILETYPE_NOTNUM_ERR = 118,
	STATUS_FILEMD5_NOTSTRING_ERR = 119,
	STATUS_IP_CHECK_ERR = 120,
	STATUS_SERVER_TIME_OUT_ERR = 121,
	STATUS_REQID_NOTNUM_ERR = 122,
	STATUS_ECHOSTR_NOTSTRING_ERR = 123,
	STATUS_TYPE_NOTNUM_ERR = 124,
	STATUS_START_TIME_NOTNUM_ERR = 125,
	STATUS_END_TIME_NOTNUM_ERR = 126,
	STATUS_COUNTRY_NOTSTRING_ERR = 127,
	STATUS_PROVINCE_NOTSTRING_ERR = 128,
	STATUS_CITY_NOTSTRING_ERR = 129,
	STATUS_BODY_CHECK_ERR = 130,
	STATUS_BODY_TYPE_CHECK_ERR = 131,
	STATUS_BODY_START_TIME_CHECK_ERR = 132,
	STATUS_BODY_END_TIME_CHECK_ERR = 133,
	STATUS_BODY_START_END_TIME_CHECK_ERR = 134,	
	STATUS_REQINFO_EMPTY_ERR = 135,
};
enum ReqBody_type
{
	ALLDATA = 0,
	URL_BLACK = 1,
	MOBILE_VIRUS = 2,
	PC_VIRUS = 3,
	DDOS_INFO = 4,
	DDOS_NEW_INFO = 5,
	GOV_URL = 6,
	
	
	CITY_URL = 100,
	CITY_URL_TYPE = 101,
	CITY_MOBILE_VIRUS = 102,
	CITY_PC_VIRUS = 103,
	CITY_DDOS = 104,
	CITY_DDOS_IP = 105,
	CITY_DDOS_NEW = 106,
	CITY_DDOS_NEW_IP = 107,
	CITY_GOV_URL = 108,

	PROVINCE_URL_EVILCLASS_DISTRIBUTE = 149,	
	PROVINCE_URL_EVILCLASS_TREND = 150,	
	PROVINCE_URL_SITE_DISTRIBUTE = 151,	
	PROVINCE_URL_HISTORY_DATA = 152,	
	PROVINCE_URL_DISTRIBUTE_COMPARE= 153,	
	PROVINCE_MOBILE_VIRUSTYPE_PROVINCE = 154,	
	PROVINCE_MOBILE_VIRUSTYPE_HISTRORY = 155,	
	PROVINCE_MOBILE_VIRUS_CITY_STAT = 156,	
	PROVINCE_MOBILE_VIRUSTYPE_PROVINCE_STAT = 157,	
	PROVINCE_PC_VIRUSTYPE_PROVINCE = 158,	
	PROVINCE_PC_VIRUSTYPE_HISTRORY = 159,	
	PROVINCE_PC_VIRUS_CITY_STAT = 160,	
	PROVINCE_PC_VIRUSTYPE_PROVINCE_STAT = 161,	
	PROVINCE_DDOS_CPT_TEN_DAY_HISTORY = 162,
	PROVINCE_DDOS_CNT_HISTORY = 163,
	PROVINCE_DDOS_STAT_TEMPLATE = 164,
	PROVINCE_DDOS_NEW_CPT_TEN_DAY_HISTORY = 165,
	PROVINCE_DDOS_NEW_CNT_HISTORY = 166,
	PROVINCE_DDOS_NEW_STAT_TEMPLATE = 167,
	PROVINCE_GOV_MONITOR_RESULT = 168,	
};


#endif
